"""Per-class-day review checklists for the prep packs (PHY 317).

Michael's standing rule (2026-09-07): every PCCI and every in-class
problem must be reviewed BEFORE the class it appears in, and every
homework SOLUTIONS must be finalized and hand-reviewed by Michael before
the set goes live (ideal) and no later than the first class after it
goes live (mandatory: students may ask about it in that class)
(assigned = the day the Moodle assignment becomes visible, 10.5 days
before it is due). This script enumerates those problems per day from
the calendar generator -- PCCI, CHAPTER_PROBLEMS, HWS -- so the lists
stay correct when the assignments change. Rerun after any generator
edit:

    python make_review_checklists.py

Writes `01-review-checklist.md` into every existing prep-pack folder
(matched by the NN- class-number prefix) and the whole-semester
`REVIEW-SCHEDULE.md` at the prep-pack root. Both are generated files;
do not edit them by hand.
"""
import re
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import make_fall2026_calendar as CAL  # noqa: E402

PACKS = Path.home() / "coding/courses/ClassicalMechanics/private/F2026PrepPacks"
AVAILABLE_DAYS_BEFORE = 10.5          # build_317.py
FIRST_CLASS = date(2026, 9, 9)

# ------------------------------------------------------------ logistics
# The bring / set-up list is checklist material (a checkbox, not prose),
# so it lives here as data rather than in the hand-written prep notes.
EVERY_DAY = [
    "iPad",
    "Four-color voting cards",
]
# date -> items specific to that day
DAY_LOGISTICS = {
    date(2026, 9, 9): ["Printed syllabus, one per student (9) + a spare",
                       "PRINT the four-color voting cards, one set per student (shared/VotingCardLandscape.pdf)"],
    date(2026, 9, 11): ["Students' LAPTOPS (announced Wednesday) for the ten-minute jupyterhub walkthrough",
                        "Your own laptop logged into jupyterhub.smith.edu with the HW01 notebook already uploaded",
                        "Check HW01 is visible on Moodle and its notebook link (GitHub) opens"],
    date(2026, 10, 9): ["Exam 1: printed copies + a spare; per-problem score sheet ready"],
    date(2026, 11, 11): ["Exam 2: printed copies + a spare; per-problem score sheet ready"],
    date(2026, 12, 7): ["Exam 3: printed copies + a spare; per-problem score sheet ready"],
    date(2026, 12, 11): ["MacBook (HDMI) for the driven-pendulum notebook; students bring laptops"],
}


def fmt(d):
    return d.strftime("%a %b %-d")


def chapter_of(reading):
    m = re.match(r"(?:Ch\.?\s*)?(\d+)", reading.strip())
    return int(m.group(1)) if m else None


def class_rows():
    """[(class_no, date, topic, reading, chapter, chapter_day)] for content
    days; exam days carry chapter None."""
    days = list(CAL.class_days())
    content = iter(CAL.CONTENT)
    seen = {}
    rows = []
    for i, d in enumerate(days):
        if i in CAL.EXAMS:
            rows.append((i + 1, d, CAL.EXAMS[i][0], "", None, None))
            continue
        topic, reading, _ = next(content)
        ch = chapter_of(reading) if reading else None
        if ch is not None:
            seen[ch] = seen.get(ch, 0) + 1
        rows.append((i + 1, d, topic, reading, ch, seen.get(ch) if ch else None))
    return rows


def hw_events():
    """[(hw, visible_date, due, covers, problems)]"""
    out = []
    for hw, due, through, chapters, covers, problems in CAL.HWS:
        vis = max(due - timedelta(days=AVAILABLE_DAYS_BEFORE), FIRST_CLASS)
        out.append((hw, vis, due, covers, problems))
    return out


def checklist(row, all_rows, hws):
    n, d, topic, reading, ch, chday = row
    lines = [f"# Review checklist -- class {n:02d}, {fmt(d)} -- {topic}", "",
             "GENERATED by SyllabusAndFirstDay/2026/make_review_checklists.py from",
             "the calendar generator; rerun it after any change to PCCIs, in-class",
             "lists, homework, or the logistics table. Do not edit by hand.",
             "CHECKLIST = everything that is a checkbox (review items, deadlines,",
             "bring/set-up). PREP NOTES = the judgment (sources, errata, the timed",
             "plan, pacing).", ""]
    # ---- before class
    lines += ["## Before class (review these yourself first)", ""]
    pcci = CAL.PCCI.get(d)
    lines.append(f"- [ ] PCCI due today: **{pcci}**" if pcci else "- [ ] PCCI due today: none")
    if ch is not None and ch in CAL.CHAPTER_PROBLEMS:
        cp = CAL.CHAPTER_PROBLEMS[ch]
        # Ch 1's lists are not split by day in Will's PDFs (one list for
        # both days); a single-list chapter shows the whole list every day.
        def day_list(key):
            lst = cp[key]
            if len(lst) == 1:
                return lst[0], " (whole-chapter list; not split by day)"
            return (lst[chday - 1] if chday - 1 < len(lst) else []), ""
        ic, note = day_list("inclass")
        la, _ = day_list("lookat")
        lines.append("- [ ] In-class problems today: "
                     + (", ".join(f"**{p}**" for p in ic) + note if ic else "none listed"))
        others = [p for p in la if not pcci or p not in pcci]
        if others:
            lines.append("- [ ] Other look-at problems for today (solutions to post): " + ", ".join(others))
    else:
        lines.append("- [ ] In-class problems today: none (not a content day)")
    # next PCCI, announced today
    later = [r for r in all_rows if r[1] > d and CAL.PCCI.get(r[1])]
    if later:
        nd = later[0][1]
        lines.append(f"- [ ] Next PCCI (announce today, due {fmt(nd)}): {CAL.PCCI[nd]}")
    # ---- homework
    lines += ["", "## Homework (solutions finalized + hand-reviewed: ideally before go-live, MANDATORY by the first class after)", ""]
    next_class = min([r[1] for r in all_rows if r[1] > d], default=None)
    prev_class = max([r[1] for r in all_rows if r[1] < d], default=None)
    any_hw = False
    for hw, vis, due, covers, problems in hws:
        goes_live_now = (prev_class is None and vis <= d) or (prev_class is not None and prev_class < vis <= d)
        if goes_live_now:
            any_hw = True
            lines += [f"- [ ] **HW{hw:02d} goes live {fmt(vis)}: solutions FINALIZED and hand-reviewed, "
                      f"MANDATORY by class today** (due {fmt(due)}). Covers {covers}.",
                      f"      Problems: {problems}"]
        if next_class is not None and d < vis <= next_class:
            any_hw = True
            lines += [f"- [ ] HW{hw:02d} goes live {fmt(vis)}, before the next class: finalize and "
                      f"hand-review its solutions NOW (the ideal deadline). Covers {covers}.",
                      f"      Problems: {problems}"]
        if due == d:
            any_hw = True
            lines.append(f"- HW{hw:02d} is DUE today 10:00 PM.")
    if not any_hw:
        lines.append("- nothing new goes live or comes due today")
    # ---- bring / set up
    lines += ["", "## Bring / set up", ""]
    for item in DAY_LOGISTICS.get(d, []):
        lines.append(f"- [ ] **{item}**")
    for item in EVERY_DAY:
        if any(item.lower() in x.lower() for x in DAY_LOGISTICS.get(d, [])):
            continue          # a bold day-specific line already covers it
        lines.append(f"- [ ] {item}")
    return "\n".join(lines) + "\n"


def main():
    rows = class_rows()
    hws = hw_events()
    packs = {int(p.name[:2]): p for p in PACKS.iterdir()
             if p.is_dir() and re.match(r"\d\d-", p.name)}
    written = 0
    sched = ["# Review schedule, whole semester (PHY 317 F2026)", "",
             "GENERATED by make_review_checklists.py; rerun after any generator edit.",
             "Rule: PCCIs and in-class problems reviewed BEFORE the class; homework",
             "HW solutions finalized and hand-reviewed before",
             "the set goes live (ideal), MANDATORY by the first class after it goes live.", ""]
    for row in rows:
        text = checklist(row, rows, hws)
        n = row[0]
        if n in packs:
            (packs[n] / "01-review-checklist.md").write_text(text)
            written += 1
        body = text.split("\n", 9)[9]          # drop the title + header note
        sched += [f"## Class {n:02d} -- {fmt(row[1])} -- {row[2]}", "", body.strip(), ""]
    (PACKS / "REVIEW-SCHEDULE.md").write_text("\n".join(sched))
    print(f"wrote REVIEW-SCHEDULE.md ({len(rows)} days) and {written} pack checklists")


if __name__ == "__main__":
    main()
